### ISSUE TITLE
Test adapter fails to retrieve WorkingDirectory from Visual Studio configuration

### ISSUE THREAD

**Issue by mwu-tow** [Microsoft/vs-boost-unit-test-adapter#67]
Whenever Boost Unit Test Adapter tries to discover or run tests, it logs the following error message:
```
Nie można pobrać elementu WorkingDirectory z konfiguracji programu Visual Studio
```

As in:
```
[11.12.2017 20:46:52 Informational] ------ Discover test started ------
[11.12.2017 20:46:53 Informational] Rejestrator zainicjowany. Rejestrowanie do pliku C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\5RESBQJP.LGW\BoostTestAdapter.dll.log
[11.12.2017 20:46:53 Informational] Odnajdywanie (ListContentDiscoverer): -> [C:\Users\mwurb\Documents\Visual Studio 2015\Projects\BoostUnitTest1\Win32\Release\BoostUnitTest1.exe]
[11.12.2017 20:46:53 Error] Nie można pobrać elementu WorkingDirectory z konfiguracji programu Visual Studio
[11.12.2017 20:46:54 Informational] Znaleziony test: BoostUnitTestSample
[11.12.2017 20:46:54 Informational] Znaleziony test: BoostUnitTest
[11.12.2017 20:46:54 Informational] ========== Discover test finished: 2 found (0:00:01,9781791) ==========
```

I use:
* Visual Studio 15.5.1
* BUTA 1.0.8.2 (installed by VS)

I can reproduce the issue reliably with the trivial Boost.Test project template. It breaks tests in my projects, as they rely on custom Working Directory and Environment — and because of the issue, custom settings are not applied.

It was once working before, I recently reinstalled VS 2017, upgrading it to the latest version. (not sure if this is the actual reason though)

**Comment by mwu-tow** [comment]
I was also able to reproduce the issue using the adapter built from this repo (with revision 3bc5a3cfc93ecdb2fca51a50c6a28e796259c7b9 — anything later won't build out of the box because of MicroBuild dependency)

The exception is thrown from this line: https://github.com/Microsoft/vs-boost-unit-test-adapter/blob/3bc5a3cfc93ecdb2fca51a50c6a28e796259c7b9/BoostTestAdapter/Utility/BoostTestRunnerCommandLineArgsEx.cs#L67

Its details:

```
System.ServiceModel.EndpointNotFoundException
  HResult=0x80131501
  Message=W elemencie net.pipe://localhost/BoostTestPackageService.d57607bb-6c87-4279-91bb-e06ca10e5c3d.3908/IBoostTestPackageService brak nasłuchującego punktu końcowego, który mógłby odebrać komunikat. Jest to często spowodowane niepoprawnym adresem lub akcją protokołu SOAP. Sprawdź właściwość InnerException (jeśli jest obecna), aby uzyskać więcej szczegółowych informacji.
  Source=mscorlib
  StackTrace:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at BoostTestShared.IBoostTestPackageService.GetDebuggingPropertiesAsync(String binary)
   at BoostTestAdapter.Utility.BoostTestRunnerCommandLineArgsEx.SetWorkingEnvironment(BoostTestRunnerCommandLineArgs args, String source, BoostTestAdapterSettings settings, IBoostTestPackageServiceWrapper packageService) in C:\dev\vs-boost-unit-test-adapter\BoostTestAdapter\Utility\BoostTestRunnerCommandLineArgsEx.cs:line 64

Inner Exception 1:
PipeException: Nie można odnaleźć punktu końcowego potoku „net.pipe://localhost/BoostTestPackageService.d57607bb-6c87-4279-91bb-e06ca10e5c3d.3908/IBoostTestPackageService” na komputerze lokalnym. 
```

Please let me know if there is any other information I should provide.

**Comment by LadislavSopko** [comment]
I did found it too, I think there is just missing try/catch around, so it will skip it succesfully.
I have resolved it in [my fork](https://github.com/xwcs/vs-boost-unit-test-adapter/commit/3d9155b6e426c356fa52bb0915bec56bf32cc80b#diff-5489d9aae16f19ba3b1633d2f74518e2)

regards 
ladislav

**Comment by mwu-tow** [comment]
@LadislavSopko 
Thank you for the response. I am not sure if your fix actually solves the problem — wouldn't "skipping it" just mean that Working Directory and Environment won't get the proper values from the MSBuild project? That would break my tests, as they rely on both of these properties (particularly the environment to get the proper PATH additions).

I'd like to try running your fork to see it for myself but I am not sure how to build it. When I try opening the solution, most of the projects fail to load (just like the main MS repo):
```
F:\temp\vs-boost-unit-test-adapter\BoostTestAdapter\BoostTestAdapter.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\BoostTestAdapter\BoostTestAdapter.csproj

F:\temp\vs-boost-unit-test-adapter\BoostTestPlugin\BoostTestPlugin.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\BoostTestPlugin\BoostTestPlugin.csproj

F:\temp\vs-boost-unit-test-adapter\VisualStudioAdapter\VisualStudioAdapter.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\VisualStudioAdapter\VisualStudioAdapter.csproj

F:\temp\vs-boost-unit-test-adapter\Antlr.DOT\Antlr.DOT.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\Antlr.DOT\Antlr.DOT.csproj

F:\temp\vs-boost-unit-test-adapter\BoostTestPackage\BoostTestPackage.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\BoostTestPackage\BoostTestPackage.csproj

F:\temp\vs-boost-unit-test-adapter\BoostTestShared\BoostTestShared.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\BoostTestShared\BoostTestShared.csproj

F:\temp\vs-boost-unit-test-adapter\ThirdPartySigning\ThirdPartySigning.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\ThirdPartySigning\ThirdPartySigning.csproj

F:\temp\vs-boost-unit-test-adapter\Antlr.DOT\Antlr.DOT.csproj : error  : The imported project "F:\temp\vs-boost-unit-test-adapter\NuGetPackages\MicroBuild.Core.0.2.0\build\MicroBuild.Core.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  F:\temp\vs-boost-unit-test-adapter\Antlr.DOT\Antlr.DOT.csproj
```

Are there any build preparation steps that I'm missing? I don't really know the C#/nuget ecosystem.

**Comment by SupSuper** [comment]
Getting the same issue, using Visual Studio 15.5.2 with Boost Test Adapter 1.0.8.2. Running the test project as a standard console app works fine. Changing the Debugging project configuration doesn't help.

@mwu-tow Go to Tools > NuGet Package Manager > Manage Packets for Solution. You should get an option to restore any missing NuGet dependencies.

**Comment by mwu-tow** [comment]
I have also reported issue through Developer Community — I'm not sure what is the best channel, so let's use them both — see https://developercommunity.visualstudio.com/content/problem/167404/boost-unit-test-adapter-fails-to-retrieve-workingd.html

@SupSuper I already tries restoring packages but all I get is `All packages are already installed and there is nothing to restore.`. Even though the `NuGetPackages` directory does not exist under my repo. Perhaps `$(NuGetPackages)` in the project files should resolve to something else?
Does the repo build for you out of the box?

**Comment by LadislavSopko** [comment]
you should do in Nuget console “nuget install nuget.config”  It will make missing folder in solution dir. do it before open solution.

Inviato da iPhone

**Comment by SupSuper** [comment]
I solved my issue, the problem was that my test program was failing when Boost.Test arguments were passed (which the Visual Studio Adapter uses to find and run specific tests): http://www.boost.org/doc/libs/1_65_1/libs/test/doc/html/boost_test/runtime_config/summary.html

@mwu-tow Make sure your test programs still work when run with parameters like --list-content.

**Comment by mwu-tow** [comment]
@LadislavSopko Thanks, `nuget install` did the trick. Had to download nuget executable, since Package Manager Console didn't recognize it. I have feeling that I missed something really obvious and basic… but nevertheless everything builds fine now.
I'll try running your fork against my project and report back the results.

@SupSuper My test programs are fine and I can run them manually. The thing is they require environment defined by MSBuild, eg. to guarantee that dependencies used to build the project are in the path (I need to be able to have side-by-side projects using different deps, depending on MSBuild properties, so I can't just hardcode the proper paths down). 
When running with debugger from VS (pressing F5), everything is fine. When run by discoverer/executor environment is wrong (checked with procmon).

**Comment by LadislavSopko** [comment]
A ok. This I didn't consider, cause I build all my dependencies for my own, and all my solution depends on what I build. (we have almost everithing boost, libxml2, mysql, sqlite, zips.., zmq, lua, and so on ..), we do all with cmake, and solution in visual is just generated, cause we need our code run also on linux.
regards
ladislav

**Comment by mwu-tow** [comment]
For anyone interested — please see https://developercommunity.visualstudio.com/content/problem/178467/boosttests-could-not-retrieve-workingdirectory-fro.html

Apparently it was reported on devcommunity by another party and this time it was not closed.
Well, at least the issue is fixed.

**Comment by jonathanmcdougall** [comment]
@mwu-tow Sorry, I'm late to the party. I opened several reports on devcom about the testing tools in the past few months. Some have been [closed as "other product"](https://developercommunity.visualstudio.com/content/problem/178469/tests-could-not-locate-debug-symbols.html), others haven't, like that one.

I'm still unclear as to the separation of responsibilities between the adapters and the Visual Studio testing tools, so I usually have no idea where I should report problems. I usually stick with devcom and hope someone will pick up on them.

As for this particular bug, I haven't been able to reproduce it in a while, so I think this issue can be closed as fixed.
